module UnovaForm
  module FieldTypes
    class Password
      INPUT_TYPE: Symbol
      VALIDATORS: Hash[Symbol, Object]
      CHARS_BY_TYPE: Hash[Symbol, Array[::String]]
      ALL: Array[::String]
      MAX_PASSWORD_LENGTH_ALLOWED: ::Integer
      PASSWORD_LENGTH: ::Integer

      def self.generate_random: -> ::String
    end
  end
end
