module UnovaForm
  module Helpers
    module InputHelper
      FILE_FIELD_DEFAULT_ICON: String
      PASSWORD_FIELD_DEFAULT_ICON: String
      SEARCH_FIELD_DEFAULT_ICON: String

      @controllers_for_types: Hash[Symbol, String]

      def controllers_for_types: -> Hash[Symbol, String]

      def remove_controller_for_type: (Symbol type) -> String?

      def add_controller_for_type: (Symbol type, String controller) -> String

      def controller_for_type: (Symbol type) -> String?

      def data_controller_of: (Symbol? | String? type, String? | Symbol? current_controller) -> String

      def field_container: (String? label, id: (String | Symbol)?, type: (String | Symbol)?, error: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, container_class: String?, label_class: String?, subcontainer_class: String?, controller: (String | Symbol)?, omit_subcontainer: bool?, options: Array[Hash[Symbol, String | bool?] & { label: String, value: String, disabled: bool?, selected: bool? }]?, required: bool) -> (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer)

      def input_field: (String? label, id: (String | Symbol)?, type: (String | Symbol)?, name: (String | Symbol)?, error: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, value: Object?, required: bool?, disabled: bool?, placeholder: String?, icon: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, is_icon_left: bool?, container_class: String?, input_class: String?, label_class: String?, icon_class: String?, rows: String, controller: (String | Symbol)?, with_controls: bool, controls_on_input: bool, min: Numeric?, max: Numeric?, step: Numeric?, pattern: String?, options: (Array[Hash[Symbol, String | bool?] & { label: String, value: String, disabled: bool?, selected: bool? }] | ^() -> Array[Hash[Symbol, String | bool?] & { label: String, value: String, disabled: bool?, selected: bool? }])?) -> (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer)

      def select_field: (String? label, id: (String | Symbol)?, type: (String | Symbol)?, name: (String | Symbol)?, error: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, value: Object?, required: bool?, disabled: bool?, placeholder: (String | Symbol)?, options: Array[Hash[Symbol, String | bool?] & { label: String, value: String, selected: bool?, disabled: bool? }]?, icon: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, is_icon_left: bool?, container_class: String?, input_class: String?, label_class: String?, icon_class: String?, controller: (String | Symbol)?, multiple: bool) -> (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer)

      def boolean_field: (String? label, id: (String | Symbol)?, type: (String | Symbol)?, name: (String | Symbol)?, error: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, value: Object?, required: bool?, disabled: bool?, placeholder: (String | Symbol)?, container_class: String?, input_class: String?, label_class: String?, controller: (String | Symbol)?, checked: bool?) -> (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer)

      def file_field: (String? label, id: (String | Symbol)?, value_type: (String | Symbol)?, name: (String | Symbol)?, error: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, value: Object?, value_url: String?, required: bool?, disabled: bool?, icon: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, remove_icon: (ActionView::Helpers::TagHelper::TagBuilder | ActiveSupport::SafeBuffer | String)?, accept: String?, container_class: String?, input_class: String?, label_class: String?, controller: (String | Symbol)?) -> untyped

      private

      def array_attr: (Array[String?] array) -> String

      def beautify_string_attr: (String string) -> String

      def random_id: -> String

    end
  end
end
